<?php
/**
 * Characterization inventory of existing public request contracts.
 * It is descriptive: tests verify that every listed entry point still exists.
 */

$contract = static function (
    string $path,
    string $method,
    string $role,
    array $requestFields,
    array $success,
    array $error,
    array $sessionKeys = []
): array {
    return [
        'path' => $path,
        'method' => $method,
        'role' => $role,
        'request_fields' => $requestFields,
        'success' => $success,
        'error' => $error,
        'session_keys' => $sessionKeys,
    ];
};

return [
    $contract('index.php', 'GET', 'public', ['reference'], ['landing_html', 'privacy_minimized_status'], ['html', 'field_errors']),
    $contract('login/index.php', 'GET_OR_POST', 'guest', ['csrf_token', 'login_id', 'password'], ['root_redirect', 'role_redirect'], ['form_feedback'], ['user_id', 'role', 'form_feedback']),
    $contract('modules/auth/login.php', 'POST', 'guest', ['csrf_token', 'login_id', 'password'], ['role_redirect'], ['form_feedback'], ['user_id', 'role', 'auth_created_at', 'auth_last_activity_at']),
    $contract('modules/auth/register.php', 'POST', 'retired_client_registration', ['csrf_token', 'first_name', 'last_name', 'email', 'password'], [], ['landing_redirect', 'form_feedback'], ['form_feedback']),
    $contract('modules/auth/verify_otp.php', 'POST', 'guest', ['csrf_token', 'otp_code'], ['role_redirect'], ['form_feedback'], ['otp_flow', 'otp_user_id', 'user_id', 'role']),
    $contract('modules/auth/resend_otp.php', 'POST', 'guest', ['csrf_token'], ['OTP_redirect'], ['form_feedback'], ['otp_flow', 'otp_user_id', 'otp_last_sent_at']),
    $contract('modules/auth/forgot_password.php', 'POST', 'guest', ['csrf_token', 'action', 'email', 'otp_code', 'password', 'confirm_password'], ['reset_flow_redirect'], ['form_feedback'], ['reset_user_id', 'reset_capability', 'otp_flow', 'otp_user_id']),
    $contract('modules/auth/logout.php', 'POST', 'authenticated', ['csrf_token'], ['index_redirect'], ['index_redirect'], ['user_id', 'role', 'csrf_token']),
    $contract('modules/queue/join_queue.php', 'POST', 'client', ['csrf_token', 'service_id', 'branch_id', 'first_name', 'last_name', 'phone_number', 'client_type'], ['ticket_redirect'], ['form_feedback'], ['user_id', 'role', 'name', 'phone']),
    $contract('queue/join/index.php', 'GET_OR_POST', 'public', ['csrf_token', 'first_name', 'last_name', 'phone_number', 'service_id'], ['scheduled_ticket_token_redirect'], ['html', 'field_errors'], ['csrf_token']),
    $contract('queue/ticket/index.php', 'GET', 'public', ['token'], ['tracker_html'], ['ticket_not_found_html'], ['csrf_token']),
    $contract('track/index.php', 'GET', 'public', ['token'], ['tracker_html'], ['ticket_not_found_html'], ['csrf_token']),
    $contract('modules/queue/public_ticket_status.php', 'GET', 'public', ['token'], ['success', 'data'], ['success', 'error']),
    $contract('modules/queue/public_reference_status.php', 'GET', 'public', ['reference'], ['success', 'data.service_name', 'data.ticket_number', 'data.status_label', 'data.counter_label', 'data.checked_in_at'], ['success', 'error']),
    $contract('modules/feedback/public_submit.php', 'POST', 'public_token', ['csrf_token', 'ticket_token', 'rating', 'comment'], ['success', 'data'], ['success', 'error', 'field_errors'], ['csrf_token']),
    $contract('public-display/index.php', 'GET', 'public', [], ['html'], ['html']),
    $contract('modules/queue/public_display_status.php', 'GET', 'public', [], ['success', 'data', 'serving', 'waiting', 'generated_at'], ['success', 'error']),
    $contract('modules/queue/ticket.php', 'GET', 'client', [], ['success', 'data'], ['success', 'error'], ['user_id', 'role']),
    $contract('modules/queue/status.php', 'GET', 'authenticated_or_display_token', ['token'], ['success', 'data.windows', 'data.next', 'data.viewer_ticket'], ['success', 'error'], ['user_id', 'role']),
    $contract('modules/queue/get_prediction.php', 'GET_OR_POST', 'authenticated', ['ticket_id', 'service_id', 'client_type', 'prediction_features'], ['success', 'predicted_wait_minutes', 'source'], ['success', 'message'], ['user_id', 'role']),
    $contract('modules/queue/void_checker.php', 'POST', 'staff', ['csrf_token'], ['success', 'voided', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/notifications/get_notifications.php', 'POST', 'client', ['csrf_token'], ['success', 'data', 'unread_count'], ['success', 'error'], ['user_id', 'role']),
    $contract('modules/notifications/mark_read.php', 'POST', 'client', ['csrf_token', 'notification_ids[]'], ['success', 'marked', 'unread_count'], ['success', 'error'], ['user_id', 'role']),
    $contract('modules/notifications/dispatch_email_jobs.php', 'POST', 'OTP_session', ['csrf_token'], ['success', 'processed', 'sent', 'failed', 'skipped'], ['success', 'message'], ['otp_user_id', 'pending_user_id', 'reset_user_id']),
    $contract('modules/feedback/submit_feedback.php', 'POST', 'client', ['csrf_token', 'ticket_id', 'rating', 'comment'], ['success'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/service_window/call_next.php', 'POST', 'staff', ['csrf_token'], ['success', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/service_window/claim_counter.php', 'POST', 'staff', ['csrf_token', 'window_id'], ['dashboard_redirect'], ['select_counter_redirect', 'form_feedback'], ['user_id', 'role', 'staff_id']),
    $contract('modules/service_window/recall_ticket.php', 'POST', 'staff', ['csrf_token', 'ticket_id'], ['success', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/service_window/start_service.php', 'POST', 'staff', ['csrf_token', 'ticket_id'], ['success', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('staff/check-in/index.php', 'GET', 'staff', [], ['html'], ['role_redirect'], ['user_id', 'role', 'staff_id']),
    $contract('modules/queue/staff_arrival_lookup.php', 'POST', 'staff', ['csrf_token', 'lookup_type', 'lookup_value'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role', 'staff_id']),
    $contract('modules/queue/staff_check_in.php', 'POST', 'staff', ['csrf_token', 'ticket_id', 'check_in_method'], ['success', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/queue/staff_walk_in.php', 'POST', 'staff', ['csrf_token', 'first_name', 'last_name', 'phone_number', 'service_id'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role', 'staff_id']),
    $contract('staff/batch-printing/index.php', 'GET', 'staff', [], ['html'], ['role_redirect'], ['user_id', 'role', 'staff_id']),
    $contract('modules/queue/create_print_batch.php', 'POST', 'staff', ['csrf_token', 'service_id', 'start_number', 'end_number'], ['application/pdf', 'Content-Disposition'], ['html', 'form_feedback'], ['user_id', 'role', 'staff_id']),
    $contract('modules/service_window/complete_ticket.php', 'POST', 'staff', ['csrf_token', 'ticket_id'], ['success', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/service_window/skip_ticket.php', 'POST', 'staff', ['csrf_token', 'ticket_id'], ['success'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/service_window/void_ticket.php', 'POST', 'staff', ['csrf_token', 'ticket_id'], ['success', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/service_window/window_status.php', 'POST', 'staff', ['csrf_token', 'status'], ['success', 'data'], ['success', 'error'], ['user_id', 'role', 'staff_id']),
    $contract('modules/settings/health_services_mgmt.php', 'GET_OR_POST', 'admin', ['csrf_token', 'action', 'service_id', 'service_code', 'service_name', 'service_encoded', 'description', 'priority_only', 'display_order', 'is_active'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/queue_summary.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/predicted_vs_actual.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/peak_hour.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/counter_performance.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/turnaround_time.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/no_show.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/staff_productivity.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/ml_accuracy.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/daily_monthly_stats.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/satisfaction.php', 'GET', 'admin', ['from', 'to', 'report'], ['success', 'data'], ['success', 'error', 'field_errors'], ['user_id', 'role']),
    $contract('modules/reports/export_csv.php', 'GET', 'admin', ['from', 'to', 'report'], ['text/csv', 'Content-Disposition'], ['text/plain'], ['user_id', 'role']),
    $contract('views/client/ticket_lookup.php', 'GET', 'public', ['ref'], ['html'], ['ticket_not_found_html']),
    $contract('display.php', 'GET', 'display_token', ['token'], ['html'], ['403_html']),
    $contract('api/auth/profile.php', 'POST', 'supabase_bearer', ['Authorization'], ['success', 'data', 'provider'], ['success', 'error']),
    $contract('api/tickets.php', 'GET_OR_POST', 'customer_or_client', ['Authorization', 'service_id', 'branch_id', 'client_type'], ['success', 'data', 'prediction', 'provider'], ['success', 'error'], ['user_id', 'role']),
    $contract('api/queue.php', 'GET', 'authenticated', ['Authorization', 'branch_id'], ['success', 'data', 'provider'], ['success', 'error'], ['user_id', 'role']),
    $contract('api/admin/reports.php', 'GET', 'admin', ['Authorization', 'report', 'from', 'to'], ['success', 'data'], ['success', 'error'], ['user_id', 'role']),
    $contract('api/admin/branches.php', 'GET_OR_POST', 'admin', ['Authorization', 'branch_id', 'name', 'address', 'active'], ['success', 'data'], ['success', 'error'], ['user_id', 'role']),
    $contract('api/admin/roles.php', 'GET_POST_DELETE', 'super_admin', ['Authorization', 'user_id', 'role'], ['success', 'data'], ['success', 'error']),
];
