<?php

testCase('Batch 8J analytics use arrival and service-start timestamps', function (): void {
    $dashboard = file_get_contents(SMARTQMS_ROOT . '/views/admin/dashboard.php') ?: '';
    $prediction = file_get_contents(SMARTQMS_ROOT . '/modules/reports/builders/predicted_vs_actual.php') ?: '';
    $exporter = file_get_contents(SMARTQMS_ROOT . '/scripts/export_ml_history.php') ?: '';

    foreach ([$dashboard, $prediction, $exporter] as $source) {
        assertStringContains('COALESCE(qt.checked_in_at, qt.issued_at)', $source);
        assertStringContains('COALESCE(qt.started_at, qt.served_at)', $source);
        assertStringContains("qt.lifecycle_status = 'completed'", $source);
    }
    assertFalseValue(str_contains($prediction, 'COALESCE(qt.served_at, qt.called_at, qt.completed_at)'));
    assertFalseValue(str_contains($exporter, 'COALESCE(qt.served_at, qt.called_at, qt.completed_at)'));
});

testCase('Batch 8J report volume excludes Scheduled appointments', function (): void {
    foreach ([
        '/modules/reports/builders/queue_summary.php',
        '/modules/reports/builders/peak_hour.php',
        '/modules/reports/builders/daily_monthly_stats.php',
    ] as $path) {
        $source = file_get_contents(SMARTQMS_ROOT . $path) ?: '';
        assertStringContains("lifecycle_status <> 'scheduled'", $source, $path);
        assertStringContains('COALESCE(checked_in_at, issued_at)', str_replace('qt.', '', $source), $path);
    }
});

testCase('Batch 8J prediction capacity uses mapped counters and per-service waiting rows', function (): void {
    $availability = file_get_contents(SMARTQMS_ROOT . '/modules/queue/service_availability.php') ?: '';
    assertStringContains('JOIN counter_services cs', $availability);
    assertStringContains('cs.counter_id = sw.window_id', $availability);
    assertStringContains('AND cs.service_id = ?', $availability);
    assertStringContains("AND lifecycle_status = 'waiting'", $availability);
    assertStringContains('AND checked_in_at IS NOT NULL', $availability);
    assertStringContains('AND service_id = ?', $availability);
});

testCase('Batch 8J model loader accepts only database-exported queue observations', function (): void {
    $pipeline = file_get_contents(SMARTQMS_ROOT . '/ml/data_pipeline.py') ?: '';
    assertStringContains('must be generated by scripts/export_ml_history.php', $pipeline);
    assertFalseValue(str_contains($pipeline, 'SOURCE_COLS'));
    assertFalseValue(str_contains($pipeline, 'build_model_frame'));
});

